name: Create Release

on:
  release:
    types: [created]

jobs:
  create_linux_release:
    needs: create_release
    runs-on: ubuntu-latest
    steps:
      - name: Create Linux Release File
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pyinstaller --onefile main.py

      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./dist/main
          asset_name: glacier_linux_x64.bin
          asset_content_type: application/octet-stream

  create_windows_release:
    needs: create_release
    runs-on: windows-latest
    steps:
      - name: Create Windows Release File
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pyinstaller --onefile main.py

      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./dist/main
          asset_name: glacier_windows_x64.exe
          asset_content_type: application/octet-stream
