name: Create Release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  create_linux_release:
    runs-on: manuelrunner
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version-file: pyproject.toml

      - name: Install Bazel
        uses: bazel-contrib/setup-bazel@0.8.1
        with:
          bazelisk-cache: true
          disk-cache: ${{ github.workflow }}
          repository-cache: true

      - name: Install Protoc
        uses: arduino/setup-protoc@v3

      - name: Install Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
          
      - name: Install dependencies
        run: poetry install --no-interaction

      - name: Create Linux Release File
        run: poetry run pyinstaller --onefile main.py
      
      - name: Rename Exe
        run: mv dist/main ecsu_linux_x64_${{ github.ref_name }}.bin

      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: ecsu_linux_x64_${{ github.ref_name }}.bin
          token: ${{ secrets.GITHUB_TOKEN }}

  create_windows_release:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version-file: pyproject.toml

      - name: Install Bazel
        uses: bazel-contrib/setup-bazel@0.8.1
        with:
          bazelisk-cache: true
          disk-cache: ${{ github.workflow }}
          repository-cache: true

      - name: Install Protoc
        uses: arduino/setup-protoc@v3

      - name: Install Poetry
        run: pip install poetry
          
      - name: Install dependencies
        run: poetry install --no-interaction

      - name: Create Windows Release File
        run: poetry run pyinstaller --onefile main.py

      - name: Rename Exe
        run: move .\dist\main.exe ecsu_win_x64_${{ github.ref_name }}.exe

      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: ecsu_win_x64_${{ github.ref_name }}.exe
          token: ${{ secrets.GITHUB_TOKEN }}
